name: deploy doc

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy doc
    needs: poetry-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
        pip install mkdocs-material mkdocstrings-python mkdocs 
        mkdocs gh-deploy --force