name: deploy doc

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: deploy doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build and deploy doc
        uses: actions/setup-python@v2
          with:
            python-version: 3.x
        run: |
          pip install mkdocs-material mkdocstrings-python mkdocs 
          mkdocs gh-deploy --force